<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Solutions 
Description: A two-column, fixed-width design for 1024x768 screen resolutions.
Version    : 1.0
Released   : 20091102

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Solutions  by Free CSS Templates</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
<style type="text/css">
.style1 {
	color: #808080;
}
.style3 {
	font-size: x-large;
}
.style5 {
	text-align: left;
}
.style6 {
	font-size: xx-large;
}
</style>
</head>
<body>
	<div id="logo">
		<h2 style="height: 77px"><span class="style6"><strong>MISSING PERSON REGISTRY SYSTEM</strong></span><a href="#"><strong><span class="style6">
		</span></strong>  </a>
		</h2>
	</div>
	<hr />
	<strong><span class="style6">
	<!-- end #logo -->
	</span></strong>
	<div id="header">
		<div id="menu">
			<ul>
				<li><a class="first" href="index.php">Home</a></li>
				<li class="current_page_item"><a href="admin.php">ADMIN LOGIN</a></li>
				<li><a href="about%20us.php">About</a></li>
				<li><a href="contact%20us.php">Contact</a></li>
				<li><a href="faq.php">FAQ</a></li>
			</ul>
		</div>
		<!-- end #menu -->
		<div id="search">
			<form method="get" action="">
				<fieldset>
				<input type="text" name="s" id="search-text" size="15" />
				<input type="submit" id="search-submit" value="GO" />
				</fieldset>
			</form>
		</div>
		<!-- end #search -->
	</div>
	<!-- end #header -->
	<!-- end #header-wrapper -->
	<div id="page">
		<div id="content">
		  <div class="post">
				<h2 class="title">REGISTRATION of LOST PERSON</h2>
				<form method="post" action="success2.php">
					<div class="style5">
	<table style="width: 100%">
		<tr>
			<td style="width: 265px">NAME</td>
			<td>
	<label id="Label2">
	<input name="name" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">PHOTO</td>
			<td>
	<label id="Label3">&nbsp;<input name="photo" type="file" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">THUMB IMPRESSION</td>
			<td>
	<label id="Label4">&nbsp;<input name="thumb" type="file" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">NIC</td>
			<td>
	<label id="Label5">
	<input name="nic" type="text" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	</label></td>
		</tr>
		<tr>
			<td style="width: 265px">AGE</td>
			<td>
	<label id="Label6">&nbsp;<input name="age" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">ADDRESS1</td>
			<td>
	<label id="Label7">&nbsp;<input name="address1" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">address2</td>
			<td>
	<label id="Label8">&nbsp;<input name="address2" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">TELEPHONE</td>
			<td>
	<label id="Label9">&nbsp; <input name="telephone" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">REGION</td>
			<td>
	<label id="Label10">&nbsp;<input name="region" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">DRESS </td>
			<td>
	<label id="Label11">&nbsp; <input name="dress" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">GENDER</td>
			<td>
	<label id="Label12">&nbsp;<select name="gender">
	<option></option>
	<option>MALE</option>
	<option>FEMALE</option>
	</select></label></td>
		</tr>
		<tr>
			<td style="width: 265px">LANGUAGE</td>
			<td>
	<label id="Label13"> 
	<input name="language" type="text" />&nbsp;&nbsp;&nbsp;</label></td>
		</tr>
		<tr>
			<td style="width: 265px">AGE GROUP</td>
			<td>
	<label id="Label14">&nbsp;<select name="agegroup">
	<option></option>
	<option>INFANTS</option>
	<option>TEENAGE</option>
	<option>CHILD</option>
	<option>ADULTS</option>
	<option>SENIORS</option>
	</select></label></td>
		</tr>
		<tr>
			<td style="width: 265px">SIGN OF IDENTIFICATION</td>
			<td>
	<label id="Label15">&nbsp;<input name="sign_of_identification" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">LAST SEEN</td>
			<td>
	<label id="Label16">&nbsp;<input name="last_seen" type="text" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">LAST DATE OF SEEN</td>
			<td><label id="Label17"><input name="last_date" type="text" value="yy-mm-dd" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">DATE OF BIRTH</td>
			<td><label id="Label18">
			<input name="date_of_birth" type="text" value="yy-mm-dd" /></label></td>
		</tr>
		<tr>
			<td style="width: 265px">OTHER RELATIVE CONTACT NUMBER</td>
			<td><label id="Label19"><input name="other_contact" type="text" /></label></td>
		</tr>
	</table>
	<label id="Label1"><span class="style3">
	<br />
	</span><br />	<input name="REGISTER" type="submit" value="REGISTER" /></label></div>
				</form>
		  </div>
		</div>
		<!-- end #content -->
		<div id="sidebar">
			<ul>
				<li>
					<h2>REGISTRATION</h2>
					<p><a href="relative.PHP">REGISTRATION OF RELATIVE WITH LOST PERSON</a></p>
					<p><a href="registration.PHP">REGISTRATION</a></p>
					<p><a href="dead.php">DEADPERSON</a></p>
				</li>
				<li>
					<h2>SEARCH</h2>
					<ul>
						<li class="style1"><a href="searching.PHP">SEARCH OF A MISSING 
						PERSON</a>&nbsp; </li>
					</ul>
				</li>
			</ul>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
	<div id="footer">
		</div>
	<!-- end #footer -->
</body>
</html>
